### ISSUE TITLE
Thank you for SimpleTask

### ISSUE THREAD

**Issue by leofontenelle** [mpcjanssen/tcljupyter#5]
When I was about to recommend it, I noticed the SimpleTask repository is read-only. Please excuse this off-topic issue and allow me to thank you for developing and maintaining the app for so long. I started using it when the official app (and so many more) stopped syncing with Dropbox, I don't even now how many years ago. Eventually I migrated my stuff from Dropbox to WebDAV, and the availability of SimpleTask WebDAV was one of the most important requisites for that. I still don't know if I'll keep using SimpleTask until I can't reinstall it anymore, if I'll try Markor, of if I'll give up todo.txt. It doesn't matter: I just wanted to thank you for all these years.

PS: now that I think of it, it was pretty meta that I added used your app to add thanking you to my todo list

**Comment by mpcjanssen** [comment]
You're welcome
